---
- name: add stebbins ppa key to apt-key
  apt_key: file=/root/stebbins_handbrake_ppa.gpg
  sudo: yes

- name: stebbins handbrake sources.list
  template: >
    src=stebbins-handbrake.list.j2
    dest=/etc/apt/sources.list.d/stebbins-handbrake.list
    force=no
  register: sources_list_result
  sudo: yes

- name: apt-get update
  apt: update_cache=true cache_valid_time=0
  when: sources_list_result.changed
  sudo: yes
